2024-04-05 - download and mod aces_1.2 config, and update nuke launcher to for aces_1.2 or aces_1.3

diff --git a/resources/bin/nuke b/resources/bin/nuke
--- a/resources/bin/nuke
+++ b/resources/bin/nuke
@@ -56,49 +56,75 @@ fi
 # Set the config_type. This string searches for the correct config file.
 # options are: 'studio' 'cg' or 'custom'. Setting to 'nuke' will unset the OCIO variable.
 
+# -------------------------------------------------------------------------- #
+# aces 1.3
 # config_type="cg" 
 # config_type="studio"
 # config_type="custom"
 
-config_type="studio"
+# -------------------------------------------------------------------------- #
+# aces_1.2
+config_type="aces_1.2"
 
 # -------------------------------------------------------------------------- #
 
 # Determine the config file pattern based on the config_type
 if [[ "$config_type" == "studio" ]]; then
     config_pattern="studio-config"
+    echo "Using Studio config"
 elif [[ "$config_type" == "cg" ]]; then
     config_pattern="cg-config"
+    echo "Using CG config"
 elif [[ "$config_type" == "custom" ]]; then
     config_pattern="custom"
+    echo "Using Custom config"
 elif [[ "$config_type" == "nuke" ]]; then
-    config_pattern=""
+    echo "Using Nuke config"
+elif [[ "$config_type" == "aces_1.2" ]]; then
+    echo "Using ACES 1.2 config"
 else
     echo "Unsupported config type: $config_type"
     exit 1
 fi
 
 # -------------------------------------------------------------------------- #
+# if config_type is 'aces_1.2' set the OCIO environment variable to ocio/aces_1.2/config.ocio, else
 
-# Search for the config file in the determined folder
-directory="$PROJEKT_PIPELINE_ROOT/ocio/$folder"
-config_file=$(find "$directory" -type f -name "*$config_pattern*.ocio" | head -n 1)
-
-# Check if the config file was found
-if [[ -z "$config_file" ]]; then
-    echo "Config file not found for pattern: $config_pattern in folder: $directory"
-    exit 1
+if [[ "$config_type" == "aces_1.2" ]]; then
+    export OCIO="$PROJEKT_PIPELINE_ROOT/ocio/aces_1.2/config.ocio"
+    echo "OCIO: $OCIO"
+    echo
+    echo "# -------------------------------------------------------------------------- #"
+    echo
+    
 fi
+
+if [[ "$config_type" != "aces_1.2" ]]; then
+    # Search for the config file in the determined folder
+    directory="$PROJEKT_PIPELINE_ROOT/ocio/$folder"
+    config_file=$(find "$directory" -type f -name "*$config_pattern*.ocio" | head -n 1)
+
+    # Check if the config file was found
+    if [[ -z "$config_file" ]]; then
+        echo "Config file not found for pattern: $config_pattern in folder: $directory"
+        exit 1
+    else
+        export OCIO="$config_file"
+        echo "OCIO: $OCIO"
+    fi
+fi
+
+
 
 # ========================================================================== #
 # This section sets the OCIO environment variable.
 # ========================================================================== #
-echo $config_file
-if [[ "$config_file" != "nuke" ]]; then
-    export OCIO="$config_file"
-else
-    export -n OCIO
-fi
+# echo $config_file
+# if [[ "$config_file" != "nuke" ]]; then
+#     export OCIO="$config_file"
+# else
+#     export -n OCIO
+# fi
 
 
 # ========================================================================== #
@@ -116,12 +142,12 @@ if [[ $PROJEKT_OS == "lin" ]];
 then 
 
     # server
-    # export PROJEKT_APPS=/s84/apps
-    # export NUKE_FONT_PATH=$PROJEKT_APPS/NUKE/fonts #fonts
-    # export nuke_root=$PROJEKT_APPS/NUKE/Nuke$nuke_version
+    export PROJEKT_APPS=/s84/apps
+    export NUKE_FONT_PATH=$PROJEKT_APPS/NUKE/fonts #fonts
+    export nuke_root=$PROJEKT_APPS/NUKE/Nuke$nuke_version
 
     # local
-    export nuke_root=/usr/local/Nuke$nuke_version
+    # export nuke_root=/usr/local/Nuke$nuke_version
 
     #check if app dir exists:
     # if [ -d "$DIRECTORY" ]; then
@@ -189,6 +215,7 @@ echo
 # ========================================================================== #
 
 
+# $nuke_root/$nuke_command -nukex $@
 $nuke_root/$nuke_command $@
 
 
